"""
Convert autoencoder_final.keras -> autoencoder_int8.tflite

INT8 post-training quantisation using the WESAD baseline windows as the
representative dataset. This is what gets flashed to the ESP32-S3.
"""
from __future__ import annotations
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

import numpy as np
import tensorflow as tf
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler

import config


def main():
    # ── Load model ────────────────────────────────────────────────────────────
    model_path = config.MODELS_DIR / "autoencoder_final.keras"
    model = tf.keras.models.load_model(model_path)
    print(f"Loaded: {model_path}")

    # ── Build representative dataset (baseline windows, preprocessed) ─────────
    z = np.load(config.FEATURES_DIR / "wesad_features.npz", allow_pickle=False)
    X, y = z["X"], z["y"]
    X_base = X[y == 1]

    imputer = SimpleImputer(strategy="median")
    X_i = imputer.fit_transform(X_base)
    scaler = RobustScaler()
    X_s = scaler.fit_transform(X_i).astype(np.float32)

    print(f"Representative dataset: {X_s.shape} (baseline windows only)")

    # ── TFLite conversion with INT8 quantisation ──────────────────────────────
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type  = tf.int8
    converter.inference_output_type = tf.int8

    def representative_data_gen():
        for sample in X_s:
            yield [sample.reshape(1, -1)]

    converter.representative_dataset = representative_data_gen
    tflite_model = converter.convert()

    # ── Save ──────────────────────────────────────────────────────────────────
    out_path = config.MODELS_DIR / "autoencoder_int8.tflite"
    out_path.write_bytes(tflite_model)

    size_bytes = len(tflite_model)
    print(f"\nSaved: {out_path}")
    print(f"Size:  {size_bytes:,d} bytes  ({size_bytes/1024:.1f} KB)")
    print(f"       (ESP32-S3 flash budget: 4 MB = 4,096 KB — "
          f"this model uses {100*size_bytes/(4*1024*1024):.2f}% of flash)")

    # ── Verify INT8 model output matches float model ──────────────────────────
    print("\nVerifying INT8 vs float32 output on 5 baseline samples...")
    interp = tf.lite.Interpreter(model_path=str(out_path))
    interp.allocate_tensors()
    inp_det  = interp.get_input_details()[0]
    out_det  = interp.get_output_details()[0]

    scale_in,  zp_in  = inp_det["quantization"]
    scale_out, zp_out = out_det["quantization"]
    print(f"  Input  quantisation: scale={scale_in:.5f}  zero_point={zp_in}")
    print(f"  Output quantisation: scale={scale_out:.5f}  zero_point={zp_out}")

    errors_float = []
    errors_int8  = []
    for i in range(5):
        x = X_s[i:i+1]

        # Float model reconstruction error
        recon_f = model.predict(x, verbose=0)
        err_f   = float(np.mean((x - recon_f) ** 2))
        errors_float.append(err_f)

        # INT8 model
        x_q = np.round(x / scale_in + zp_in).astype(np.int8)
        interp.set_tensor(inp_det["index"], x_q)
        interp.invoke()
        recon_q = interp.get_tensor(out_det["index"])
        recon_dq = (recon_q.astype(np.float32) - zp_out) * scale_out
        err_q = float(np.mean((x - recon_dq) ** 2))
        errors_int8.append(err_q)

        print(f"  sample {i}: float_err={err_f:.5f}  int8_err={err_q:.5f}  "
              f"delta={abs(err_f - err_q):.5f}")

    mean_delta = np.mean([abs(f - q) for f, q in zip(errors_float, errors_int8)])
    print(f"\n  Mean absolute error delta (float vs INT8): {mean_delta:.5f}")
    if mean_delta < 0.05:
        print("  Quantisation accuracy: ACCEPTABLE")
    else:
        print("  Quantisation accuracy: ELEVATED — consider float16 instead")

    # ── Save quantisation params for ESP32 C header ───────────────────────────
    header_path = config.MODELS_DIR / "autoencoder_quant_params.h"
    with open(header_path, "w") as f:
        f.write("// Auto-generated by export_tflite.py — do not edit manually\n")
        f.write("// Preprocessing parameters for the autoencoder feature pipeline\n\n")
        f.write("#pragma once\n\n")
        f.write(f"#define AE_N_FEATURES     {X_s.shape[1]}\n")
        f.write(f"#define AE_LATENT_DIM     4\n\n")
        f.write(f"// RobustScaler: x_scaled = (x - center) / scale\n")
        center_str = ", ".join(f"{v:.6f}f" for v in scaler.center_)
        scale_str  = ", ".join(f"{v:.6f}f" for v in scaler.scale_)
        med_str    = ", ".join(f"{v:.6f}f" for v in imputer.statistics_)
        f.write(f"static const float AE_IMPUTER_MEDIAN[{X_s.shape[1]}]"
                f" = {{{med_str}}};\n")
        f.write(f"static const float AE_SCALER_CENTER[{X_s.shape[1]}]"
                f" = {{{center_str}}};\n")
        f.write(f"static const float AE_SCALER_SCALE[{X_s.shape[1]}]"
                f" = {{{scale_str}}};\n\n")
        f.write(f"// INT8 quantisation params (from TFLite)\n")
        f.write(f"#define AE_INPUT_SCALE    {scale_in:.8f}f\n")
        f.write(f"#define AE_INPUT_ZP       {zp_in}\n")
        f.write(f"#define AE_OUTPUT_SCALE   {scale_out:.8f}f\n")
        f.write(f"#define AE_OUTPUT_ZP      {zp_out}\n")
    print(f"\nC header saved -> {header_path}")


if __name__ == "__main__":
    main()