// Auto-generated by export_tflite.py — do not edit manually
// Preprocessing parameters for the autoencoder feature pipeline

#pragma once

#define AE_N_FEATURES     10
#define AE_LATENT_DIM     4

// RobustScaler: x_scaled = (x - center) / scale
static const float AE_IMPUTER_MEDIAN[10] = {0.005672f, 0.019278f, 2.250000f, 0.083659f, 70.086624f, 65.159912f, 90.035645f, 0.398046f, 0.000000f, 33.593834f};
static const float AE_SCALER_CENTER[10] = {0.005672f, 0.019278f, 2.250000f, 0.083659f, 70.086624f, 65.159912f, 90.035645f, 0.398046f, 0.000000f, 33.593834f};
static const float AE_SCALER_SCALE[10] = {0.009504f, 0.020178f, 1.000000f, 1.000000f, 9.363317f, 34.840607f, 50.483128f, 1.249815f, 1.000000f, 1.431730f};

// INT8 quantisation params (from TFLite)
#define AE_INPUT_SCALE    0.05854225f
#define AE_INPUT_ZP       -78
#define AE_OUTPUT_SCALE   0.02394544f
#define AE_OUTPUT_ZP      -38
