// Auto-generated by tremor_classifier.py
#pragma once

#define TR_FS_ACC            32
#define TR_N_FFT             128
#define TR_FREQ_RES          0.2500f

#define TR_PD_BAND_LO        4.0f
#define TR_PD_BAND_HI        6.0f
#define TR_ET_BAND_LO        8.0f
#define TR_ET_BAND_HI        12.0f

#define TR_PD_THRESH         0.35f
#define TR_ET_THRESH         0.35f
#define TR_INDET_THRESH      0.20f
#define TR_REST_THRESH       0.050f
#define TR_MOTION_MAX        0.30f
#define TR_MOTION_MIN        0.005f
#define TR_MIN_CONSECUTIVE   6
